### ISSUE TITLE
Free Reroll

### ISSUE THREAD

**Issue by KarstenW76** [Genii-Locorum/outgunned#1]
Hi, I do like your module very much, it is great. Would you mind adding a choicebox for functionality of a free Reroll? Reroll and All-In seems to be working correctly, also Danger and Gamble. But I cannot choose Free Reroll, so I have to check back the deleted Success. And I cannot make the Reroll, when I got no success on the first dice-throw (there should be only the option for a free reroll).
Thank you for checking.

**Comment by Genii-Locorum** [comment]
Leave it with me and I'll look in to it once I've upgraded the system to Foundry V12.

**Comment by KarstenW76** [comment]
> Leave it with me and I'll look in to it once I've upgraded the system to Foundry V12.

I founde the issue, there were only two lines in the wrong sequence. I tested locally and everything is working now :). I created a Pull request, would be perfect if you approve. Thank you!

**Comment by Genii-Locorum** [comment]
Approved, merged and new release created.

Thank you for fixing this Karsten
