### ISSUE TITLE
Editable Grit icons on Characters

### ISSUE THREAD

**Issue by babel2uk** [Genii-Locorum/outgunned#11]
One of the Action Flicks set-ups includes cyberware, most of it can mostly be covered by the existing items set up, however, one of the pieces of cyberware affects the Grit boxes on the character - specifically it changes the Bad box to a second Hot box. 

Would it be feasible to give the ability to edit the Grit icons on a character in the same way as you can on the Enemy sheet to let you change boxes to hot, normal, or bad as required (obviously with the standard set-up as the default) - I've not seen anything so far that affects the number of boxes, just the type?

Best
Matt

**Comment by Genii-Locorum** [comment]
> One of the Action Flicks set-ups includes cyberware, most of it can mostly be covered by the existing items set up, however, one of the pieces of cyberware affects the Grit boxes on the character - specifically it changes the Bad box to a second Hot box.
> 
> Would it be feasible to give the ability to edit the Grit icons on a character in the same way as you can on the Enemy sheet to let you change boxes to hot, normal, or bad as required (obviously with the standard set-up as the default) - I've not seen anything so far that affects the number of boxes, just the type?
> 
> Best Matt

Is it just the 8th box that changes?  If so then I could add a status (perhaps a tick box on the Description tab) that changes it to a "hot" box.  Or can you changed other normal grit (e.g. 5) to hot as well?

**Comment by babel2uk** [comment]
It is just that existing Bad box that switches to a hot box instead, so if it's simpler to limit it to just that one changing then that works for me. :)On 21 Sept 2024 15:47, Genii-Locorum ***@***.***> wrote:

One of the Action Flicks set-ups includes cyberware, most of it can mostly be covered by the existing items set up, however, one of the pieces of cyberware affects the Grit boxes on the character - specifically it changes the Bad box to a second Hot box.
Would it be feasible to give the ability to edit the Grit icons on a character in the same way as you can on the Enemy sheet to let you change boxes to hot, normal, or bad as required (obviously with the standard set-up as the default) - I've not seen anything so far that affects the number of boxes, just the type?
Best Matt

Is it just the 8th box that changes?  If so then I could add a status (perhaps a tick box on the Description tab) that changes it to a "hot" box.  Or can you changed other normal grit (e.g. 5) to hot as well?

**Comment by Genii-Locorum** [comment]
OK - I think this is done just for the 8th box  
![og](https://github.com/user-attachments/assets/8201ca43-d856-4ed1-82f0-e7b178289189)

**Comment by babel2uk** [comment]
Looks great to me 😀

**Comment by Genii-Locorum** [comment]
Thank you for your input.  Now fixed in release V2.08.  I will close the issue.
