### ISSUE TITLE
New Gamble roll type (Razors Edge Gamble)

### ISSUE THREAD

**Issue by babel2uk** [Genii-Locorum/outgunned#12]
One of the Action Flicks (Neon Noir) adds a more extreme type of Gamble roll, which might be something that would be best made available on the dice roller via a game control rather than always being present - though it's obviously easy enough  to ignore if hiding it is fiddly. 

Taking a Razors Edge Gamble gives you a +2 die bonus to your roll, but causes 3 Grit damage for every Snake Eye rolled.

Best
Matt

**Comment by Genii-Locorum** [comment]
@babel2uk 

So on a roll the Gamble option would become No, Yes and Razor's Edge (rather than just No & Yes)?

It's easy enough to add a game setting to activate Razor's Edge as an option (and it's hidden unless this is turned on).

Have I got that right?

**Comment by babel2uk** [comment]
That's right. It's basically just an upgraded version of a Gamble, so an extra option in the drop down sounds perfect. 🙂On 21 Sept 2024 15:50, Genii-Locorum ***@***.***> wrote:
@babel2uk
So on a roll the Gamble option would become No, Yes and Razor's Edge (rather than just No & Yes)?
It's easy enough to add a game setting to activate Razor's Edge as an option (and it's hidden unless this is turned on).
Have I got that right?

**Comment by Genii-Locorum** [comment]
Here you go - tested the damage and it works

![og](https://github.com/user-attachments/assets/e9168be2-f7b2-4484-86a4-8a40a45ff06c)

**Comment by Genii-Locorum** [comment]
![og2](https://github.com/user-attachments/assets/ef4f6507-565d-4af8-bc44-bc69003a4ef0)

**Comment by babel2uk** [comment]
Awesome work

Thanks 😀

**Comment by Genii-Locorum** [comment]
Thank you for your input.  Now fixed in release V2.08.  I will close the issue.
