### ISSUE TITLE
Adventure conversion

### ISSUE THREAD

**Issue by babel2uk** [Genii-Locorum/outgunned#13]
I'm still looking through the rules. Would it be helpful if I uploaded a copy of the character sheet for you to look at? I'm happy to add any or all of these as separate tickets, but figured it'd be useful for you to have an overview first.

Much of the changes between Adventure and Outgunned seem to be cosmetic.

**Labels**
"Background" instead of "Job" 
"Treasure" instead of "Mission"
"Luck" instead of Adrenaline

**Enemy Grit Box icons**
Something that might be needed is the ability to switch the icons on the Enemy sheet Grit track between Normal, Hot and Bad (Adventure doesn't use Adrenaline for normal bad guys - and Supernatural Threats get up to 3 "Bad" boxes in their track and use one of their Special Powers when one is filled in).

### **Weapons and Gear**
Weapons are basically identical to Outgunned. They do bring in Melee Weapons as something of a hybrid (they're identical to Outgunned - where they're just considered Gear, but they can have Weapon Feats attached to them). Probably not worth changing the way they work as it's only a couple of traits and they are narrative.

**Storage**
Gear storage is separated into On Person, Bag or Backpack instead of just "On Person" and "Storage" (on the printed character sheet Bag sits where the Ride section is). "On Person" allows anything that it's feasible you'd be carrying in pockets, in a holster, over your shoulder etc, including up to 3 weapons (only one of which may have "Bulky" as a Weapon feat);  "Bag" can only hold smaller items; "Backpack" is larger storage and can hold all kinds of items, as well as up to 3 additional weapons (with the same restriction to a single "Bulky" weapon).

**Rides**
Can either be ignored entirely (there's no section for them on the sheet) or can use the Outgunned ride format, so no changes required, unless you want to add a toggle to show/hide the Rides section on the sheet.

**Key Item(s)**
This is basically just a gear item that is crucial to the adventure. Obviously it's easy enough to denote that in the item name, but it's be nice if there was some way of adding a symbol or something to the item to make it stand out in the gear list (regardless of where it's being carried). Rule-wise it's an item that you can never lose (outside of 4 specific circumstances) just because you fail a roll - you instead fill in a Grit box (or suffer a Condition) to represent you hurting yourself to save the item.

Best
Matt

**Comment by Genii-Locorum** [comment]
@babel2uk   This sounds like a fair few things to work through - but happy to keep it as 1 issue for now (although I may finish the other ones first).

If it's not breaking copyright then yes, a copy of the character sheet would be handy.

Cheers

Simon

**Comment by babel2uk** [comment]
@Genii-Locorum Here's a copy of one of the sheets from their Quickstart for Adventure. I can't see sharing that with you being an issue since it's a pay what you want download from Drivethrurpg.
[Jason.pdf](https://github.com/user-attachments/files/17098228/Jason.pdf)

**Comment by Genii-Locorum** [comment]
Right - I think I'm there with these - so here's the approach I've taken - if something doesnt work we can figure it in the next release.

There is a game setting for "Game Version" - at the moment Outgunned or Adventures.  We can do more another time

Labels - these now automatically change on the game version

Enemy Grit Box icons - when using Adventure you get an extra context menu option to set individual grit items to "Bad"

Melee Weapons - I've not made any changes for this

Storage- when using Adventure In storage appears as "In Backpack" - on person and in bag remain the same.  They don't get separate lists though on the character sheet

Rides - I've not made any changes,  but yell if you really want the option to turn "Rides" tab off.

Key Item(s) - you can only change the status in the gear sheet (not directly on the character sheet - to avoid accidental clicks).  Key Items have a red key icon before the name

Got a bit of tidying up to do and probably some instructions to write but hopefully this will be released shortly.

**Comment by Genii-Locorum** [comment]
Version 9 released
