### ISSUE TITLE
Conditions affecting Multiple Skills or Attributes

### ISSUE THREAD

**Issue by babel2uk** [Genii-Locorum/outgunned#14]
The "Smeared Through" condition (aka "Slimed") from the Ghost Hunters Action Flick affects two skills (Flirt and Style) rather than an attribute or single skill. Is it feasible to add another skill selection drop-down to the Conditions set up? For flexibility it may be worth looking at giving the ability to just add additional Attribute or skill drop-downs to a Condition item, that way if there are new ones brought in that affect several attributes, or which affect a bunch of skills, it's covered.

Best
Matt

**Comment by Genii-Locorum** [comment]
If I gave the option to add Two Skills and Two attributes |(with not applicable always being an option) would that work?

Maximum flexibility (at least until we hit a condition that could affect three or more).

**Comment by babel2uk** [comment]
Sounds good to me :)On 21 Sept 2024 15:55, Genii-Locorum ***@***.***> wrote:
If I gave the option to add Two Skills and Two attributes |(with not applicable always being an option) would that work?
Maximum flexibility (at least until we hit a condition that could affect three or more).

**Comment by Genii-Locorum** [comment]
@babel2uk  - quick question whilst I'm out doing the grocery shopping....

If I have two conditions that can affect the same skill is that -2 to dice roll or just -1.

Does the same apply to attributes?

Cheers

**Comment by babel2uk** [comment]
Sorry, was out myself.As far as I can tell, they stack, so if there's 2 conditions affecting one skill or attribute it would be -2. With the caveat that you can never be rolling more than 9 or less than 2 dice.On 22 Sept 2024 10:51, Genii-Locorum ***@***.***> wrote:
@babel2uk  - quick question whilst I'm out doing the grocery shopping....
If I have two conditions that can affect the same skill is that -2 to dice roll or just -1.
Does the same apply to attributes?
Cheers

**Comment by Genii-Locorum** [comment]
Thank you for your input.  Now fixed in release V2.08.  I will close the issue.
