### ISSUE TITLE
Unable to assign the 2 free skills.

### ISSUE THREAD

**Issue by JasonSunday** [Genii-Locorum/outgunned#15]
The Free Skills only shows Fight and when I add another skill to the character sheet it doesn't add new skills available for the free skills.
![unable to assign skills](https://github.com/user-attachments/assets/c58664c8-db44-4008-9f3c-83f1d89cb782)

**Comment by Genii-Locorum** [comment]
Can you post screenshots of the Fight and Awareness skills from the character sheet and also a pic of what skills you've got in the game world please.

The code should pull all Skills in the game world and only exclude those where the skill is already on the character sheet and the total score is 3+.

And sorry for the delay in coming back to you (just back from holiday

**Comment by dmpunks** [comment]
Confirmed. You need to import all the Skills into the world (i.e. they should be in the Items tab).
