### ISSUE TITLE
Create a character sheet without making Role and Trope compendium

### ISSUE THREAD

**Issue by francois-robert** [Genii-Locorum/outgunned#16]
Hello,

Maybe it's me but is there a way to create a character sheet without having to create entries for desired role and compendium ? I just want to create the caracters from the quickstart.

**Comment by Genii-Locorum** [comment]
@francois-robert Sort of.  The GM can edit skills and attributes if they turn on the Freeform Edit tool (under Outgunned Tools), but they can't add a Trope, Age or Role name.  I will look to add these for the next release.

What other functionality do you need to make this work?  Do you want the player to be able to make the changes or just the GM?

**Comment by francois-robert** [comment]
Thanks for your answer. I wasn't aware of the Freeform Edit tool, it fullfills excactly my need.
