### ISSUE TITLE
help with pt-br translation!

### ISSUE THREAD

**Issue by Xulinha** [Genii-Locorum/outgunned#6]
Hii, I've been in love with outgunned for a long time and really interested about playing at Foundry with my friends but some of them dont know a single line in english. I cant code for life but I have knowledge and a dream, just wanted to know if theres something I can do to contribute and/or help

**Comment by xKuPeD** [comment]
Hi there, here for help for FR translation if needed. Don't know what to do, but keep me in touch. :)

**Comment by Genii-Locorum** [comment]
Hi

Sorry - I’m away on holiday until start of Sept so responding is sporadic.

In the lang folder there are two file en.json and de.json

Copy one of those and rename it from.json

Then where you see things like “awareness” : “Awareness” change the second one after the : to the French equivalent.

If you do this in your local installation the. Send me the file I can make the system. JSON changes when I’m back from holiday.

Keep a backup copy of your fr.json file and if you have any questions please shout and I’ll try and answer.

Cheers

Simon

Sent from my iPhone

On 17 Aug 2024, at 09:31, xKuPeD ***@***.***> wrote:

﻿

Hi there, here for help for FR translation if needed. Don't know what to do, but keep me in touch. :)

**Comment by Genii-Locorum** [comment]
I should also say there’s a discord thread here

<https://discord.com/channels/843177526317940778/1252573916313157632>
[og_img_discord_home.png]
Group Chat That’s All Fun & Games<https://discord.com/channels/843177526317940778/1252573916313157632>
discord.com<https://discord.com/channels/843177526317940778/1252573916313157632>


Karsten W did the German translation so may be able to help whilst I’m away

Thanks

Simon

Sent from my iPhone

On 17 Aug 2024, at 09:56, Simon Hill ***@***.***> wrote:

﻿ Hi

Sorry - I’m away on holiday until start of Sept so responding is sporadic.

In the lang folder there are two file en.json and de.json

Copy one of those and rename it from.json

Then where you see things like “awareness” : “Awareness” change the second one after the : to the French equivalent.

If you do this in your local installation the. Send me the file I can make the system. JSON changes when I’m back from holiday.

Keep a backup copy of your fr.json file and if you have any questions please shout and I’ll try and answer.

Cheers

Simon

Sent from my iPhone

On 17 Aug 2024, at 09:31, xKuPeD ***@***.***> wrote:

﻿

Hi there, here for help for FR translation if needed. Don't know what to do, but keep me in touch. :)

**Comment by xKuPeD** [comment]
can we get an invit for discord server ? 
Have a nice holiday ! :)

**Comment by KarstenW76** [comment]
Hi and great, you want to support with further translations.

here‘s the invite link for 2LM Discord: https://discord.gg/XDf648TW

I have some experience with translations, but also on vacation at the moment 😏.
But if you have questions I’ll try to help directly, but please via Discord PM, write me there please …: KarstenW

**Comment by Xulinha** [comment]
Already finished the translation, just not sure about something but when u guys back we can talk more, enjoy the vacations

**Comment by KarstenW76** [comment]
If you like you can write me on discord and send me the file there. Or upload it here as attachment, so I can take a look.
What is it, you’re unsure about?

**Comment by xKuPeD** [comment]
Are we both translating FR Xulinha ?

**Comment by Xulinha** [comment]
> Are we both translating FR Xulinha ?

No Im not, just pt-br 😉

**Comment by Xulinha** [comment]
> If you like you can write me on discord and send me the file there. Or upload it here as attachment, so I can take a look.
> What is it, you’re unsure about?

Sure, Ill upload when I get home. I was unsure about some terms I used and if they would look good at the interface or dont look like I just droped words at google translate u know

**Comment by KarstenW76** [comment]
> Sure, Ill upload when I get home. I was unsure about some terms I used and if they would look good at the interface or dont look like I just droped words at google translate u know

Ah ok, wait, you should check all those by yourself. Easiest way to do (where you don’t need to modify any files) is the following:

1. you already copied the en.json and changed the name. Make a backup from the original en.json.
2. Change you’re edited json to en.json and put in where the English one actually is (in the Outgunned system).
3. just reload your outgunned world, then you don’t see it in English but in your language. Then you can check the length of the translations and if all looks right and if anything is at the right place and correctly translated.
4. when you’re fine with everything, you can test and play with it . Parallely send us this file with the right changed name for what you want to translate.

With our next  release version, you’re locally en.json will be overwritten to English again, but then you’ll find your language to select.

**Comment by Xulinha** [comment]
> Are we both translating FR Xulinha ?

Oh now I got what u were trying to say sorry if I sounded rude 😭, sorry but I dont know french so well, did some classes but am no longer studying but if u have any issue pls tell me I can try and help u

**Comment by Xulinha** [comment]
Im home now and making the final adjustments, later Ill send the archive or if u prefer I can wait till september

**Comment by Xulinha** [comment]
Also very important, is there a way I can set the skills and other thing from the compendium translated so it will be available for other players?

**Comment by Xulinha** [comment]
Pressed the wrong buttons LOL, but I was going to also ask if theres a way I can let the skills and other thing from the foundry compendium already translated for other players, because if just send the translation archive only half of the character sheet will be translated for example

**Comment by KarstenW76** [comment]
Best read the instructions provided with the compendium. System is build the way, that only items in the world, not the ones in the compendium, are taken into the character sheet.
The attributes are translated in the language json file.
The skills, talents, conditions etc. are items which you create in your world and in your language.
When you create a new character then, all those world items are automatically imported and shown in your sheet.

this way you’re able to create f.e. compendiums for different settings, action flicks or so, and can import the package you need for your game ready to go.

**Comment by Genii-Locorum** [comment]
V2.06 has been released with the French language pack (thank you everyone who input).

@Xulinha - given Karsten's answers are you happy for me to close this issue?

Cheers

Simon
