### ISSUE TITLE
Core Rules Free Skill Points and Gear & New Weapon Feats

### ISSUE THREAD

**Issue by babel2uk** [Genii-Locorum/outgunned#7]
Hi,

I have some queries, which I don't know whether they could be fixed within your agreement with TLM....

1. The Core Rules give characters 2 free skill points after they have added Role and Trope. Is there any way to add this without using the Advancements, or would that be feasible as a development?
2. Under the core rules, you get 1 in ALL skills as a base. I just realised that when creating a character, only the skills from the Role and Trope are added to the sheet, so you have to drag the rest of the skills on. Could all of the skills appear by default?
3. The Core rules give set gear options for Roles (in some cases they are a choice between items), are there any plans to include Gear options into the character creation automation?
4. One of the closed issues talks about Weapons Feats from World of Killers, and your response says that these can be added yourself, but that you can't add them due to your agreement with TLM. How can I add a new custom weapon feat, or is that not possible?

Thanks for your time and for putting this together :)

Best
Matt

**Comment by Genii-Locorum** [comment]
Hi @babel2uk.  I'm back from holiday and will try to find some time to start looking at this but I have a lot of stuff to catch up on with other systems as well.  Just wanted to let you know you're not being ignored.
Cheers

Simon

**Comment by babel2uk** [comment]
No worries, thanks for taking the time to let me know. :)BestMattOn 16 Sept 2024 17:33, Genii-Locorum ***@***.***> wrote:
Hi @babel2uk.  I'm back from holiday and will try to find some time to start looking at this but I have a lot of stuff to catch up on with other systems as well.  Just wanted to let you know you're not being ignored.
Cheers
Simon

**Comment by Genii-Locorum** [comment]
@babel2uk 

Hi Matt

1) In the next release (hopefully this evening) I've added a GM Freeform edit tool that will allow GMs to change the base, role, trope and XP scores on Attributes and Skills on a character sheet.  Hopefully this will let you resolve issue 1 (albeit its a GM having to do it)
2) This should already happen for "character" actors but only adds skills from the world (not from Compendia).  If you're still getting problems with this can you please open up a new issue for that.
3) I don't have any immediate plans but this is doable (I've got some similar code for another system that I can reuse).  I will add it to the project plan but don't have any timeframe to do this.
4) I clearly was having a funny moment then - no you can't add custom weapon feats - my bad.  Are there a lot of new weapon feats?  A few options spring to mind
  a) I add the feats to the code (as it's just a word and icon with no discussion of the rules I don't think this breaches the spirit of the agreement with TLM (i.e. you'll still need to buy the rules)
  b) I change "feats" to simply be a text input box where you can write whatever you like in there
  c) Create weapon feats as an item and let you drag and drop these on to weapons - more complex but doable and means you can homebrew without it just being a text box

I'd welcome your thoughts on the above.

Cheers

Simon

**Comment by babel2uk** [comment]
Hi Simon,

1. Obviously, ultimately it would be good if the player could do so themselves somehow (maybe add an additional line with 2 diamonds in the Edit window called "Free Points", and allow any players to toggle those diamonds - I'm assuming there's something in the code that says that you can have a maximum of 3 diamonds filled in on skills) but certainly in the short term that solves the issue for me.
2. I've tested and at the moment I still only get the skills from the Role and Trope appearing on the sheet, and have to drag the rest on. It's not a big problem, but it'd be more user-friendly if all of the basic skills appeared by default on the sheet at rank 1, and dropping the Role and Trope on just added to them.
3. No worries on that - though having looked at it a bit more, it might be a nightmare to code. Many of the Roles do have a set gear list, but then you get the ones that have choices between 2 set items, and some that just have "any $1 item".
4. As far as I can tell there are 11 new weapon feats split between Action Flicks and World of Killers: 
World of Killers = CUSTOM, TRADITIONAL, INCENDIARY
Action Flicks = LASER, MAXIMUM POWER, MUZZLE-LOADING, TOY, GHOSTPROOF, STREAM, ANTI-VAMPIRE, ANTI-WEREWOLF
I recently got the stand-alone Adventure genre book, and there are a bunch of additional/differently named feats in the core, and likely more in the action flicks supplement for that, it depends on whether you're looking to make the system useable for that as well. There are some other differences between the two, but I think from a character sheet point of view those differences are mostly just different names (e.g. Luck instead of Adrenaline) and icons, which are probably pretty simple to do as an alternate character sheet.
I'm all for keeping a simple approach and the text box would be the easiest and most flexible. I do like the buttons, and the icons in the Weapon List (though the icons can be difficult to see - curse my eyesight!), but hard-coding the feats as buttons and icons would probably mean looking at it again next time TLM put out a new action flick or genre book. Adding Weapons Feats as dragable items would likely be a lot of effort for no real benefit other than a specific look, so my advice would be to save yourself the headache on that one.

Thanks for looking at this.

**Comment by HandOfCthulhu** [comment]
FWIW:
1. Came to post this issue as well. Feel like best option is as babel2uk described, a separate diamond set for the "free skill points" If it is easier in the short term adding a second diamond for trope (the system instructions in the system's compendium already say that the free skill point is attached to the trope) that can then be checked by the GM editing the stat for a particular character would be a fine hack.
2. I added all of the skills (from the core + WoK anyway) to my item inventory and created a new character and it seemed to populate all of the skills correctly.
3. While nice, agree this is definitely a stretch goal.
4. I would prefer in the long run an implementation of weapon feats as a separate item that slots into weapons, making it easy (after initial data entry) to drag and drop them into new weapons, and creates options to automate them in the future. But textbox would be fine for a quick and dirty fix.
5. With 90+% of the same DNA I'd prefer OGA be included in the same outgunned system. Any rule differences implemented via the system settings.

**Comment by Genii-Locorum** [comment]
Thanks for the input @HandOfCthulhu  and @babel2uk  - let me have a think and poke around the code to see what I can do.

As background - I originally wrote the system as a teach in on how to create a system for Foundry so a lot of what I did isn't consistent or necessarily the best way - it was more a showcase of blocks of code on how to do things in different ways.  I did try to do some polishing when I was asked to release it - but still lots more to do and it's only by getting feedback like this that will improve the system.  So there are places where I've limited functionality to GMs only but if you think players should be able to do stuff (like changing attribute points, skill points etc) then please call it out.

And I will put my hands up - I've not played OG - so again your input is invaluable as you actually run games and know what works for your GMs and players.

**Comment by babel2uk** [comment]
Actually I just realised (thanks to HandOfCthulhu's comment) that I'd been a complete muppet on the default skills question. Now that I've imported the skills from the Compendium into the World (which I now realise is what you meant in your original reponse) it's working properly and showing all of the skills in the list when creating a new character. :)

With regard to the weapon feats.... I've been looking through, and I suspect they are impossible to automate in any meaningful way (at least with a reasonable amount of effort). The idea of being able to set up a list of feats and drag them into a new weapon item is fair enough, but for me at least it's likely quicker and easier to copy and paste the line out of the rulebook pdf. I guess the benefit to having them as dragable items would be the possibility of having the feat description pop up when hovering over it - though it's likely just as easy to give the players access to a handout with all of those descriptions on. The effects of the feats are just too wide ranging and inconsistent to feed meaninfully into the dice roller.

I'll make an effort to look through the supplements and Adventure and see whether there's anything that couldn't reasonably be handled by the current set up. as HandOfCthulhu said it's 90+% the same system, so most changes will likely be cosmetic.

Cheers
Matt

**Comment by Genii-Locorum** [comment]
Phew - glad that the skills bit is sorted.  So point 2 cleared.

@babel2uk  @HandOfCthulhu 

Point 1 - I've just made changes to my working copy (will go out in the next release if this works for you both)

Free Skill points are now separate to Trope - they still get added when you add a trope, but removing the trope doesn't clear the point. 

On the Description tab of the character sheet there's a new heading "Free Skill" - the number is the number of points spent.  There's a context menu that let's you clear all the points spent or let's you spend "unspent" points.  For both this and the trope option you only get to select skills to take you to 2 points (so if you've spent two points it does nothing).

The GM still has the option with Freeform edit to make changes and isn't restricted by the 2 point limit.

![image](https://github.com/user-attachments/assets/318ac3b2-63d7-4c82-a8dd-db3a9346b98d)

I'll now start thinking about point 4.  My initial thought was to have a new item type that had a name, longer description and an icon.  I won't automate the impact as this would be a mammoth task.

Let me know what you think about the Free Skill changes.

Cheers

Simon

**Comment by HandOfCthulhu** [comment]
Looks good to me!

**Comment by babel2uk** [comment]
Looks good to me too. :)

**Comment by babel2uk** [comment]
OK, I'm going to open a bunch of tickets based on what I've found in World of Killers and Action Flicks mostly I'm ignoring anything that can be easily handled with the current set-up (i.e if they're feats or simply narrative rules for the setting) - I'm sure @HandOfCthulhu will be able to comment on them or add more. I'll also open a single ticket for Adventure at the moment because mostly it's cosmetic changes for that. I appologise in advance for the mini heart attack you'll have when you see a bunch of tickets appear....

Best
Matt

**Comment by Genii-Locorum** [comment]
> Looks good to me too. :)
> 
> While I'm still happy with the idea of just having a text field for weapon feats, if you're happy to go down the route of developing a new item type that can be dropped onto a weapon then that works for me too.

What can I say, I like the challenge.

**Comment by Genii-Locorum** [comment]
> OK, I'm going to open a bunch of tickets based on what I've found in World of Killers and Action Flicks mostly I'm ignoring anything that can be easily handled with the current set-up (i.e if they're feats or simply narrative rules for the setting) - I'm sure @HandOfCthulhu will be able to comment on them or add more. I'll also open a single ticket for Adventure at the moment because mostly it's cosmetic changes for that. I appologise in advance for the mini heart attack you'll have when you see a bunch of tickets appear....
> 
> Best Matt

No worries, and thanks for taking the time to add them - no idea how quickly I can resolve them,

**Comment by Genii-Locorum** [comment]
@babel2uk  @HandOfCthulhu 

Hopefully the last question/review on this Issue and then I will release a new update and close this topic.

I've finished coding Weapon Feats (a lot quicker than I imagined due to reusing code)
![og](https://github.com/user-attachments/assets/308cf039-9516-4131-a0f7-0ddaa264959c)

On the right you see two Weapon Feats - top one shows the attribute tab with the FAS Icon (you enter this so will need to understand/look them up - tooltip points you to the website) and the Description is on the description tab.  If you can't see an icon on the attributes tab it means the icon doesn't exist.

Bottom left is a gun and you now drag and drop the feats  to the sheet - it shows the name and the icon.

Top left is the character sheet - so essentially it's no different (just pulls data from the new Feats area) - again if you've not got a valid icon it won't show here.

So two questions
1) Does this do what you want
2) At this stage I won't delete the old "feats" toggle boxes to give people a chance to update to the new method (I can't really do a conversion script as it would mean creating and distributing new items and I'm loathe to do that).  I would remove the visibility/data in a while.  Alternatively I could move the info to another tab on the gun that is visible to the GM only and delete that in due course.   

Thoughts, and thank you.

**Comment by HandOfCthulhu** [comment]
Looks reasonable to me!

**Comment by babel2uk** [comment]
Looks good to me too. Quick question - is it possible for the person creating the weapon feat item to add or change the icon?

**Comment by Genii-Locorum** [comment]
> Looks good to me too. Quick question - is it possible for the person creating the weapon feat item to add or change the icon?

Short answer is not easily/quickly.  Foundry doesn't really handle embedding items within items - so the weapon feat that's added is a series of data points in an array rather than an actual item.  SO I can't use existing code to edit an weapon feat item - I'd have to write some code from scratch to edit the data within the weapon itself.

So whilst it is doable, I figure people would rather have the extra functionality from the other issues instead of this.

**Comment by babel2uk** [comment]
No problem, figured it was better to ask now than have you say later "well if you'd asked earlier...." 😀

**Comment by Genii-Locorum** [comment]
Thank you for your input.  All items now fixed in release V2.08 or added to project plan.

I will now close the issue.
