### ISSUE TITLE
Plan B markers

### ISSUE THREAD

**Issue by babel2uk** [Genii-Locorum/outgunned#8]
Could markers be added on all Character sheets - linked and marked for everyone like the Heat level is? These would either need to feed from one character sheet across all the others - or be toggled by buttons in the Outgunned tools like Heat is.

Ultimately it might be worth looking at whether it is feasible to have a panel in the game window that shows current Heat, and which of the Plan B options are used and which are still available, and have the raise/lower heat controls and the use Plan B controls incorporated into that.

Some Action Flicks add new Plan B options that replace specific existing ones, but they really are just renamed, 
Swashbucking action flick replaces "Bullet" with "Blade"
Wierder Things action flick replaces it with "Beat"
Midnight Wars replaces it with "Blood" or "Beast". 

Being able to replace the name and icon would be fantastic, but not absolutely required.

Best
Matt

**Comment by Genii-Locorum** [comment]
Hi Matt

How about:
1) I create three game settings - PlanB1, PlanB2, PlanB3 that have a name and an icon (these will default to Bullet, BackUp, Bluff but the GM can change them and the icons).
2) GM has a tool to toggle them on/off individually as they are used
3) They appear on the character sheets in a new heading below heat - three icons with tooltip for the name

So visible on the character sheet at all times, only GM can activate and they can be changed to suit the game.

Let me know what you think

Cheers

Simon

**Comment by babel2uk** [comment]
That sounds good to me :)

**Comment by Genii-Locorum** [comment]
Two screenshots - first is the game settings with the default

Second shows the GM tools, how Plan B is on the character sheet and the alert message when its triggered.

Should go out in a release this weekend.

![og1](https://github.com/user-attachments/assets/2c8b4192-1010-491d-94a9-63cc7eef451c)
![og2](https://github.com/user-attachments/assets/0941195d-3fe6-4fb6-a6ba-b90a81b806a8)

**Comment by babel2uk** [comment]
Awesome! Looks great!

**Comment by Genii-Locorum** [comment]
Thank you for your input.  Now fixed in release V2.08.  I will close the issue.
