### ISSUE TITLE
Rides - new types and Item visibility

### ISSUE THREAD

**Issue by babel2uk** [Genii-Locorum/outgunned#9]
**Ride Types**
Some of the Action Flicks bring in new Ride Types: 
- Starship (icon looks like a spacefighter, but a rocket is probably a good substitute)
- Beasts (well, horses, and it says you can use the Bike type for this, but there's a key difference in rolls used - Stunt instead of Drive - so I think it's worth a stand-alone category, and an icon of a horse is probably a good choice)
- Non-motorized (basically bicycles, skateboards etc that are powered by the user's muscles - the icon used in the book is a pushbike)

**Items section on Rides**
In the Ride item type, can the label for "Items" be changed to "Extras" instead?  
Would it be feasible for the Items/weapons that are added to the Extras section on a Ride appear in the Ride section of the character sheet? Maybe a Guns and Gear section on each would work best, as some vehicles will have built in weapons, or other gadgets.

Best
Matt

**Comment by Genii-Locorum** [comment]
@babel2uk 

Hi Matt.  Will this do?

![og](https://github.com/user-attachments/assets/b931dce4-65d1-4b80-b37a-dd7d2cbd8702)

**Comment by babel2uk** [comment]
It absolutely  will! 😃

**Comment by Genii-Locorum** [comment]
Thank you for your input.  Now fixed in release V2.08.  I will close the issue.
